# Generated by Django 5.2 on 2025-11-15 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_contributor_works_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositorywork",
            name="contributor",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="work",
        ),
        migrations.RemoveField(
            model_name="repositorywork",
            name="repository",
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("abstract", models.TextField(help_text="Paper abstract")),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "journal",
                    models.CharField(
                        blank=True,
                        help_text="Journal or conference name",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("citation_count", models.IntegerField(default=0)),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, help_text="List of keywords/topics"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to paper (arXiv, DOI resolver, etc.)"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="Journal/publisher logo", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated summary of the paper"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Raw API response data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publication_date", "-citation_count"],
                "indexes": [
                    models.Index(
                        fields=["-publication_date"],
                        name="api_paper_publica_4363ce_idx",
                    ),
                    models.Index(
                        fields=["-citation_count"], name="api_paper_citatio_2eb31c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="University or institution",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "orcid_id",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier",
                        max_length=19,
                        null=True,
                        unique=True,
                    ),
                ),
                ("h_index", models.IntegerField(default=0, help_text="h-index metric")),
                (
                    "research_interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of research interests/topics",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to researcher profile (Google Scholar, personal page, etc.)"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="AI-generated summary of researcher's work"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, help_text="Raw API response data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-h_index", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="api_researc_name_e8ba7d_idx"),
                    models.Index(
                        fields=["-h_index"], name="api_researc_h_index_8530fd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Authorship",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "author_position",
                    models.CharField(
                        blank=True,
                        help_text="Author position (first, corresponding, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contribution_role",
                    models.CharField(
                        blank=True,
                        help_text="Specific contribution (methodology, analysis, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Summary of this researcher's specific contributions to this paper"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="api.paper",
                    ),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="api.researcher",
                    ),
                ),
            ],
            options={
                "ordering": ["paper", "id"],
                "unique_together": {("paper", "researcher")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reviewer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("peer_review", "Peer Review"),
                            ("revision_request", "Revision Request"),
                            ("acceptance", "Acceptance"),
                            ("rejection", "Rejection"),
                        ],
                        default="peer_review",
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to review if available", null=True
                    ),
                ),
                ("summary", models.TextField(help_text="Summary of review comments")),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.authorship",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "version_number",
                    models.CharField(
                        help_text="Version identifier (v1, v2, etc.)", max_length=50
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(help_text="Link to this version")),
                ("summary", models.TextField(help_text="Changes in this version")),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.authorship",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.DeleteModel(
            name="Commit",
        ),
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.DeleteModel(
            name="Issue",
        ),
        migrations.DeleteModel(
            name="Repository",
        ),
        migrations.DeleteModel(
            name="RepositoryWork",
        ),
    ]
