# Generated by Django 5.2 on 2025-11-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_repositorywork_contributor_remove_issue_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="semantic_scholar_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Semantic Scholar paper ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="semantic_scholar_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Semantic Scholar author ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
