# Generated by Django 5.2 on 2025-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_paper_semantic_scholar_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="abstract",
            field=models.TextField(
                blank=True, default="", help_text="Paper abstract", null=True
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI-generated summary of the paper",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to paper (arXiv, DOI resolver, etc.)",
                null=True,
            ),
        ),
    ]
