# Generated by Django 5.2 on 2025-11-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_paper_abstract_alter_paper_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.IntegerField(help_text="Total number of papers to import"),
                ),
                (
                    "processed",
                    models.IntegerField(
                        default=0, help_text="Number of papers processed so far"
                    ),
                ),
                (
                    "successful",
                    models.IntegerField(
                        default=0, help_text="Number of successfully imported papers"
                    ),
                ),
                (
                    "failed",
                    models.IntegerField(
                        default=0, help_text="Number of failed imports"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of errors: [{title, error}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job finished", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_importj_created_813a69_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_importj_status_b6c955_idx"
                    ),
                ],
            },
        ),
    ]
