# Generated by Django 5.2 on 2025-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_importjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="duplicates",
            field=models.IntegerField(
                default=0, help_text="Number of duplicate papers skipped"
            ),
        ),
    ]
