# Generated by Django 5.2 on 2025-11-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_importjob_duplicates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPublication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "semantic_scholar_id",
                    models.CharField(
                        db_index=True,
                        help_text="Semantic Scholar paper ID",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Publication year", null=True
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Journal/conference name",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("citation_count", models.IntegerField(default=0)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_imported",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this paper has been imported to Paper model",
                    ),
                ),
                (
                    "last_fetched",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this data was last fetched from API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_publications",
                        to="api.researcher",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-citation_count"],
                "indexes": [
                    models.Index(
                        fields=["researcher", "-year"],
                        name="api_externa_researc_5c405b_idx",
                    ),
                    models.Index(
                        fields=["researcher", "semantic_scholar_id"],
                        name="api_externa_researc_5c7337_idx",
                    ),
                    models.Index(
                        fields=["last_fetched"], name="api_externa_last_fe_94d3b0_idx"
                    ),
                ],
                "unique_together": {("researcher", "semantic_scholar_id")},
            },
        ),
    ]
