# Generated by Django 5.2 on 2025-11-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_externalpublication"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="affiliation_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Career history: [{institution, role, start_year, end_year, ror_id}]",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="affiliations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Full list of affiliations: [{name, years, ror_id}]",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="aliases",
            field=models.JSONField(
                blank=True, default=list, help_text="Alternative name spellings"
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="current_position",
            field=models.CharField(
                blank=True, help_text="Current job title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="data_quality_score",
            field=models.FloatField(
                default=0.0, help_text="Completeness score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="data_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of data sources used: ['semantic_scholar', 'orcid', ...]",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="dblp_pid",
            field=models.CharField(
                blank=True, help_text="DBLP person ID", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="GitHub username", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="i10_index",
            field=models.IntegerField(
                default=0, help_text="i10-index (papers with 10+ citations)"
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="last_enriched",
            field=models.DateTimeField(
                blank=True, help_text="When this profile was last enriched", null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="openalex_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OpenAlex author ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="paper_count",
            field=models.IntegerField(
                default=0, help_text="Total number of publications"
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="primary_research_area",
            field=models.CharField(
                blank=True, help_text="Main research field", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="research_concepts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Research concepts with scores: [{concept, score, level}]",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="research_statement",
            field=models.TextField(
                blank=True, help_text="Research statement or bio", null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="scopus_id",
            field=models.CharField(
                blank=True, help_text="Scopus author ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="total_citations",
            field=models.IntegerField(default=0, help_text="Total citation count"),
        ),
        migrations.AddField(
            model_name="researcher",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Whether profile has been verified"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="affiliation",
            field=models.CharField(
                blank=True,
                help_text="Current university or institution",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="orcid_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ORCID identifier",
                max_length=19,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="raw_data",
            field=models.JSONField(
                blank=True,
                help_text="Raw API response data from all sources",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of researcher's work",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Link to researcher profile (Google Scholar, personal page, etc.)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["-total_citations"], name="api_researc_total_c_5b77c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["-paper_count"], name="api_researc_paper_c_78a0ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researcher",
            index=models.Index(
                fields=["last_enriched"], name="api_researc_last_en_f75d6b_idx"
            ),
        ),
    ]
