# Generated by Django 5.2 on 2025-11-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_researcher_affiliation_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="data_source",
            field=models.CharField(
                blank=True,
                help_text="Primary data source (semantic_scholar, openalex, crossref)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="import_attempted_at",
            field=models.DateTimeField(
                blank=True, help_text="When enrichment was last attempted", null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="import_failure_reason",
            field=models.TextField(
                blank=True, help_text="Reason for import failure", null=True
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of paper enrichment import",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="openalex_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OpenAlex work ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
